apiVersion: v1
kind: Pod
metadata:
  name: memory-hog
spec:
  containers:
  - name: memory-hog
    image: debian:stretch-slim
    command: [ "bash", "-c", "arr=(); while true; do arr+=($(head -c 1048576 -n 1 /dev/urandom | xxd -p)); done" ]
    resources:
      limits:
        memory: "100Mi"
